# -*- coding: utf-8 -*-
"""getter-setter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cMaNUnZ7i4__QANe44usRAmgfAPg4n2D
"""

class CadPessoa():
  '''Classe de alteração cadastral de funcionários de uma empresa'''
  def __init__(self, nome, cidade, salario):
    self.nome = nome
    self.cidade = cidade
    self.sal = salario

  def get_nome(self):
      return self.nome

  '''Métodos getter e setter do atributo cidade'''
  def get_cidade(self):
      return self.cidade

  def set_cidade(self, city):
      self.cidade = city

  '''Métodos getter e setter do atributo salário'''
  def get_sal(self):
    return self.sal

  def set_sal(self, salar):
    self.sal = salar

'''Objetos'''
p1 = CadPessoa('Gustavo', 'Recife', 1000)
print('Nome: ', p1.get_nome())
print('Cidade: ', p1.get_cidade())
print('Salário em reais: ', p1.get_sal())
newsal = int(input('Digite o novo salário:'))
p1.set_sal(newsal)
print('Salário em reais após alteração: ', p1.get_sal())

p2 = CadPessoa('Guilherme', 'Olinda', 1000)
print('Nome: ', p2.get_nome())
print('Cidade: ', p2.get_cidade())
print('Salário em reais: ', p2.get_sal())
newcity = str(input('Digite a nova cidade que a pessoa reside: '))
p2.set_cidade(newcity)
print('Cidade atual: ', p2.get_cidade())