# -*- coding: utf-8 -*-
"""manip-string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lFWk2hRXusrgUmF4-bEO9fjM-0ME5LMw
"""

frase1 = str(input('Digite uma frase curta: '))
print('A frase capitalizada fica: ')
print(frase1.capitalize())
print('A frase com todas as letras em caixa alta fica: ')
print(frase1.upper())
print('A frase com todas as letras minúsculas fica: ')
print(frase1.lower())
print('A frase invertida fica: ')
print(frase1[::-1])